#define USAGE_SOCCONTROL "SocControl"
#define USAGE_FIRMWARETRANSFER "FirmwareTransfer"
#define USAGE_FIRMWAREFILEID "FirmwareFileId"
#define USAGE_FILEOFFSETINBYTES "FileOffsetInBytes"
#define USAGE_FILETRANSFERSIZEMAXINBYTES "FileTransferSizeMaxInBytes"
#define USAGE_FILEPAYLOAD "FilePayload"
#define USAGE_FILEPAYLOADSIZEINBYTES "FilePayloadSizeInBytes"
#define USAGE_FILEPAYLOADCONTAINSLASTBYTES "FilePayloadContainsLastBytes"
#define USAGE_FILETRANSFERSTOP "FileTransferStop"
#define USAGE_FILETRANSFERTILLEND "FileTransferTillEnd"


#define USAGE_PAGE_SOC {"SoC", {\
	{1, USAGE_SOCCONTROL},\
	{2, USAGE_FIRMWARETRANSFER},\
	{3, USAGE_FIRMWAREFILEID},\
	{4, USAGE_FILEOFFSETINBYTES},\
	{5, USAGE_FILETRANSFERSIZEMAXINBYTES},\
	{6, USAGE_FILEPAYLOAD},\
	{7, USAGE_FILEPAYLOADSIZEINBYTES},\
	{8, USAGE_FILEPAYLOADCONTAINSLASTBYTES},\
	{9, USAGE_FILETRANSFERSTOP},\
	{10, USAGE_FILETRANSFERTILLEND},\
}}
